### ISSUE TITLE
datetimeV2 for Italian LUIS project

### ISSUE THREAD

**Issue by ECocca** [MicrosoftDocs/azure-docs.it-it#275]
I tried to create a new italian project on LUIS portal, but when I add a prebuilt entity I can only see datetime instead of datetimeV2. The same thing in another project where I wanted to replace datetime entity with datetimeV2 entity. Is it only available for English project?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e64e2485-bcef-05c1-ee5a-10a0f3be7275
* Version Independent ID: f5adced3-6007-4fdb-51ba-cb95f16bbee6
* Content: [Entità predefinite DatetimeV2 - Azure](https://docs.microsoft.com/it-it/azure/cognitive-services/luis/luis-reference-prebuilt-datetimev2#feedback)
* Content Source: [articles/cognitive-services/LUIS/luis-reference-prebuilt-datetimev2.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cognitive-services/LUIS/luis-reference-prebuilt-datetimev2.md)
* Service: **cognitive-services**
* Sub-service: **language-understanding**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@ECocca Thank you for reporting this. The [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#italian-entity-support) appears to be different from the LUIS portal. I'm not sure which is correct. #in-progress.

**Comment by CeciAc** [comment]
@diberry should I move this to the en-us repo?

**Comment by diberry** [comment]
@CeciAc Only if you want - I already have a fix in the docs on the english side.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32382](https://github.com/MicrosoftDocs/azure-docs/issues/32382) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ECocca 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32382

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

cc @diberry
