### ISSUE TITLE
feedbackReceiver.ReceiveAsync(); non funziona

### ISSUE THREAD

**Issue by Istorn** [MicrosoftDocs/azure-docs.it-it#348]
Ho implementato la procedura tale e quale l'avete specificata voi stessi in questa guida.

Alla riga "var feedbackBatch = await feedbackReceiver.ReceiveAsync();" il programma termina automaticamente senza alcun messaggio né tantomeno a livello di console.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ba79df4d-c64b-7950-3ae9-6f28ea94409b
* Version Independent ID: 7ad0c568-0df2-3be8-f221-0fb846bf575c
* Content: [Messaggi da cloud a dispositivo con l'hub IoT di Azure (.NET)](https://docs.microsoft.com/it-it/azure/iot-hub/iot-hub-csharp-csharp-c2d)
* Content Source: [articles/iot-hub/iot-hub-csharp-csharp-c2d.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/iot-hub/iot-hub-csharp-csharp-c2d.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34871](https://github.com/MicrosoftDocs/azure-docs/issues/34871) via [**ZenHub**](https://www.zenhub.com/)
