### ISSUE TITLE
Documentation or lab + issue

### ISSUE THREAD

**Issue by gpitzalis** [MicrosoftDocs/azure-docs.it-it#366]
Is there a lab or a more detailed documentation of this component? We are trying to use it in an enterprise scenario, we are able to browse the open hub tables collection but, once we have configured one and execute the pipeline, we are not reading any data from the source. Any idea about this behavior? Thanks!

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6445960a-ba4e-8e08-d9a7-326d35f902b6
* Version Independent ID: fddcb50b-f74e-ce0d-af42-991587f456ca
* Content: [Copiare dati da una tabella SAP usando Azure Data Factory](https://docs.microsoft.com/it-it/azure/data-factory/connector-sap-table#feedback)
* Content Source: [articles/data-factory/connector-sap-table.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/data-factory/connector-sap-table.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by srvbpigh** [comment]
Hello, @gpitzalis
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @gpitzalis

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by gpitzalis** [comment]
Ok but please also provide some example bacause actually the documentation is poor in my opinion.
