### ISSUE TITLE
pg_dump with output redirection produces corrupted archive (at least in Powershell 5.1.17763.592)

### ISSUE THREAD

**Issue by lorenzo-biava** [MicrosoftDocs/azure-docs.it-it#402]
The backup example uses the output redirection to create the dump file. In Powershell 5.1.17763.592 that results in a corrupted file, which is not recognized by pg_restore.
The example might be updated with the `-f` argument to specify the output file:
`pg_dump -h MySourceServerName -U MySourceUserName -Fc -d MySourceDatabaseName -f Z:\Data\Backups\MyDatabaseBackup.dump`

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 43b2566e-1fc7-cf49-512a-794f56760672
* Version Independent ID: fe824068-38f3-d7db-260f-e2af6e5fa7a1
* Content: [Come eseguire il dump e il ripristino nel database di Azure per PostgreSQL-server singolo](https://docs.microsoft.com/it-it/azure/postgresql/howto-migrate-using-dump-and-restore#feedback)
* Content Source: [articles/postgresql/howto-migrate-using-dump-and-restore.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/postgresql/howto-migrate-using-dump-and-restore.md)
* Service: **postgresql**
* GitHub Login: @rachel-msft
* Microsoft Alias: **raagyema**

**Comment by srvbpigh** [comment]
Hello, @lorenzo-biava
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39050](https://github.com/MicrosoftDocs/azure-docs/issues/39050) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @lorenzo-biava

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/39050

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
