### ISSUE TITLE
Block blob storage account è tradotto come "Bloccare"

### ISSUE THREAD

**Issue by Gnafu** [MicrosoftDocs/azure-docs.it-it#410]
The titles should be reviewed

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 06288d35-3c83-c29d-95d8-a56823d910a3
* Version Independent ID: 002fb5f5-5e4a-a95a-4564-2c399bcb5e06
* Content: [Panoramica dell'account di archiviazione di Azure](https://docs.microsoft.com/it-it/azure/storage/common/storage-account-overview)
* Content Source: [articles/storage/common/storage-account-overview.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/storage/common/storage-account-overview.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @Gnafu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Gnafu

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
