### ISSUE TITLE
Use of MFA in Office 365 Business Premium not clear

### ISSUE THREAD

**Issue by MavBoss86** [MicrosoftDocs/azure-docs.it-it#423]
It's not clear what is provided with the Office 365 Business Premium subscription. With these licenses can I activate the MFA to only some users? Have they access also to Phone Call/SMS MFA? The table and the phrase on top ("There is no ability to only enable multi-factor authentication for a subset of users, or only under certain scenarios") are in contrast. The Office 365 Portal permit to activate this type of MFA with this license that is different from the MFA enabled with the Security Defaults (that enables only the app as second factor).

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: feb03e63-f543-d85b-9daf-16b4d1e13a60
* Version Independent ID: da9dcdd2-70d4-e08e-18f2-6e6a1489937a
* Content: [Versioni di Azure Multi-Factor Authentication e piani di utilizzo](https://docs.microsoft.com/it-it/azure/active-directory/authentication/concept-mfa-licensing#feedback)
* Content Source: [articles/active-directory/authentication/concept-mfa-licensing.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/active-directory/authentication/concept-mfa-licensing.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @MavBoss86
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @MavBoss86,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
