### ISSUE TITLE
Supporto delle lingue

### ISSUE THREAD

**Issue by Alemaudit** [MicrosoftDocs/azure-docs.it-it#424]
Forse preferibile riscrivere "Supporto dei linguaggi di programmazione"?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 18fb3b37-8ba1-579c-ceb4-329c283f107a
* Version Independent ID: 0ead5f4c-63a0-d782-0a89-b5d612596d89
* Content: [Funzionalità di Azure Cloud Shell](https://docs.microsoft.com/it-it/azure/cloud-shell/features#feedback)
* Content Source: [articles/cloud-shell/features.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cloud-shell/features.md)
* Service: **azure**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by srvbpigh** [comment]
Hello, @Alemaudit
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Ciao @Alemaudit:

Grazie per il contributo. 

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati. 

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche. 

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto. 

Grazie per il supporto. 

Team di Microsoft DOCS Global Experience
