### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by vicobiscotti** [MicrosoftDocs/azure-docs.it-it#425]
At the end of step 5, the list does not appear. A Home with "Welcome" inside appears. The header contains "Home" and "Privacy", but the content is not the expected list.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: c8d9b842-de22-59e7-e36a-662e2060ae7a
* Version Independent ID: bda934c5-a268-721f-1a3e-1f73fc25c15f
* Content: [Esercitazione sull'app Web MVC ASP.NET Core con Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/sql-api-dotnet-application?source=docs#feedback)
* Content Source: [articles/cosmos-db/sql-api-dotnet-application.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cosmos-db/sql-api-dotnet-application.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-sql**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by srvbpigh** [comment]
Hello, @vicobiscotti
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49978](https://github.com/MicrosoftDocs/azure-docs/issues/49978) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Il tuo contributo è molto apprezzato. I tuoi commenti e suggerimenti sono correlati alla documentazione originale.  

Di conseguenza, questa segnalazione verrà inoltrata all'archivio in lingua inglese. Puoi verificare lo stato della segnalazione qui - vicobiscotti.  

Il tuo contributo ai nostri articoli è molto apprezzato.   

Cordiali saluti,  
Il team internazionale Microsoft Docs
