### ISSUE TITLE
After the critical day 29th Febraury

### ISSUE THREAD

**Issue by NicolasPSQ** [MicrosoftDocs/azure-docs.it-it#426]
Hello,
i'm in a partner tenant. This page is cool, but i don't finish to understand if from the 1st March the conditional access are active yet?. Because, more than application incluse Veeam Backup for Office 365 not work. Is there something to do to enable again this type of apps?

Thanks

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: cfac0ecf-e5a9-c5ff-f8c2-ce27789708f5
* Version Independent ID: 0f5e0cc9-a54f-a5c8-192d-d60a6a4db3ff
* Content: [Impostazioni predefinite sicurezza Azure Active Directory](https://docs.microsoft.com/it-it/azure/active-directory/fundamentals/concept-fundamentals-security-defaults#feedback)
* Content Source: [articles/active-directory/fundamentals/concept-fundamentals-security-defaults.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/active-directory/fundamentals/concept-fundamentals-security-defaults.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @NicolasPSQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @NicolasPSQ , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
