### ISSUE TITLE
I'm not able to retrieve the data added with the Xamarin.Forms application from the SQL Database.

### ISSUE THREAD

**Issue by TheKlingon** [MicrosoftDocs/azure-docs.it-it#428]
Hi. 
I followed the document for the Xamarin.Forms app, but this doesn't receive the data from the database. 
I'm searching for a solution, but I'm wondering if there is something wrong into the document.
Thanks.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: c4467b7b-c082-73d2-5626-038fb12d25a3
* Version Independent ID: b9874b73-5524-6238-ea70-a23d8a27aa47
* Content: [Introduzione a Novell. Forms](https://docs.microsoft.com/it-it/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started#feedback)
* Content Source: [articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started.md)
* GitHub Login: @lucasfmo

**Comment by TheKlingon** [comment]
![Annotazione 2020-03-18 041057](https://user-images.githubusercontent.com/8925451/76921620-c5d76200-68ce-11ea-9928-3b4324010796.jpg)
![image](https://user-images.githubusercontent.com/8925451/76922169-4054b180-68d0-11ea-902f-c60b2f20da4a.png)
![image](https://user-images.githubusercontent.com/8925451/76922206-52365480-68d0-11ea-8852-9a6af075f286.png)

**Comment by srvbpigh** [comment]
Hello, @TheKlingon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @TheKlingon, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50435. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
