### ISSUE TITLE
Storage account premium not supported

### ISSUE THREAD

**Issue by Dan-cws** [MicrosoftDocs/azure-docs.it-it#429]
With a block blob storage it is not possibile to create a Standard Akamai CDN. The origin is not listed when creating the endpoint and if added after the creation it does not work

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 38ede72f-b8be-6455-36b8-e891451f42a0
* Version Independent ID: f97e246c-4076-c4bb-e1df-34d05edea0fd
* Content: [Avvio rapido - Integrare un account di archiviazione di Azure con la rete CDN di Azure](https://docs.microsoft.com/it-it/azure/cdn/cdn-create-a-storage-account-with-cdn)
* Content Source: [articles/cdn/cdn-create-a-storage-account-with-cdn.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cdn/cdn-create-a-storage-account-with-cdn.md)
* Service: **azure-cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by srvbpigh** [comment]
Hello, @Dan-cws
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @Dan-cws , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
