### ISSUE TITLE
Separazione degli altoparlanti (diarizzazione)

### ISSUE THREAD

**Issue by voisis-support** [MicrosoftDocs/azure-docs.it-it#430]
La trascrizione automatica mi pare abbia fallito

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 73fb7e76-fb80-c420-2efe-e3ca3a27b749
* Version Independent ID: 07a42557-deb3-e4b3-3f14-f26a27be49c2
* Content: [Che cos'è la trascrizione batch - Servizio di riconoscimento vocale - Azure Cognitive Services](https://docs.microsoft.com/it-it/azure/cognitive-services/speech-service/batch-transcription#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/batch-transcription.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cognitive-services/Speech-Service/batch-transcription.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by srvbpigh** [comment]
Hello, @voisis-support
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Ciao @voisis-support 

Grazie per il contributo. 

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati. 

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche. 

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto. 

Grazie per il supporto. 

Team di Microsoft DOCS Global Experience
