### ISSUE TITLE
Mistakes on diminesion in Dav4 table

### ISSUE THREAD

**Issue by redaniel74** [MicrosoftDocs/azure-docs.it-it#432]
Hi all,
can you re-typing storage throughput values in Megabytes and not in Megabits .

Thanks,
Red

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6db9f5c3-21ed-49da-ae37-7e5d1bed1dce
* Version Independent ID: 49ce3600-c7fa-8cdc-1283-154e28b7e7a7
* Content: [Serie Dav4 e Dasv4 - Macchine virtuali di Azure](https://docs.microsoft.com/it-it/azure/virtual-machines/dav4-dasv4-series?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json&bc=%2Fazure%2Fvirtual-machines%2Flinux%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [articles/virtual-machines/dav4-dasv4-series.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/virtual-machines/dav4-dasv4-series.md)
* Service: **virtual-machines**
* GitHub Login: @migerdes
* Microsoft Alias: **jushiman**

**Comment by srvbpigh** [comment]
Hello, @redaniel74
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @redaniel74  

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
