### ISSUE TITLE
Imprecisione nella documentazione

### ISSUE THREAD

**Issue by mdesimoneIWG** [MicrosoftDocs/azure-docs.it-it#434]
Volevo segnalare che al lemma "Nell'esperienza di Configurazione guidata di Windows, l'aggiunta di un dominio Active Directory (AD) locale non è supportata. Se si prevede di aggiungere un computer a un dominio AD, durante l'installazione è necessario selezionare il collegamento Configurare Windows con un account locale. Sarà quindi possibile aggiungere il dominio dalle impostazioni del computer." si fà menzione alla non possibilità di aggiungere il pc al dominio locale, ciò è però possibile tramite Windows Autopilot tramite il connettore di Intune. Sarebbe opportuno aggiornare tale paragrafo. 
Saluti.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 7a7a5351-21c0-946d-fdc0-5e1943aa0a01
* Version Independent ID: acf0eb8d-109f-c3b4-b862-adb61ae8fdc7
* Content: [Aggiungere un nuovo dispositivo Windows 10 con Azure AD in fase di completamento dell'installazione](https://docs.microsoft.com/it-it/azure/active-directory/devices/azuread-joined-devices-frx#feedback)
* Content Source: [articles/active-directory/devices/azuread-joined-devices-frx.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/active-directory/devices/azuread-joined-devices-frx.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @mdesimoneIWG
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54018](https://github.com/MicrosoftDocs/azure-docs/issues/54018) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Il tuo contributo è molto apprezzato. I tuoi commenti e suggerimenti sono correlati alla documentazione originale.  

Di conseguenza, questa segnalazione verrà inoltrata all'archivio in lingua inglese. Puoi verificare lo stato della segnalazione qui - mdesimoneIWG.  

Il tuo contributo ai nostri articoli è molto apprezzato.   

Cordiali saluti,  
Il team internazionale Microsoft Docs
