### ISSUE TITLE
l livello di coerenza del prefisso coerente

### ISSUE THREAD

**Issue by baleng** [MicrosoftDocs/azure-docs.it-it#436]
"Il livello di coerenza del prefisso coerente garantisce che le Scritture non vengano mai visualizzate in modo corretto" 
deve essere 
"l livello di coerenza del prefisso coerente garantisce che le Scritture non vengano mai visualizzate in modo disordinato"

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 2b3fb7da-5483-160d-1781-d4abff9d798d
* Version Independent ID: d5e51b7e-7f34-c7df-ce4f-ee4bf5c8059a
* Content: [Livelli di coerenza in Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/consistency-levels?source=docs#feedback)
* Content Source: [articles/cosmos-db/consistency-levels.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cosmos-db/consistency-levels.md)
* Service: **cosmos-db**
* GitHub Login: @markjbrown
* Microsoft Alias: **mjbrown**

**Comment by srvbpigh** [comment]
Hello, @baleng
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Ciao @baleng 

Grazie per il contributo. 

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati. 

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche. 

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto. 

Grazie per il supporto. 

Team di Microsoft DOCS Global Experience
