### ISSUE TITLE
PowerBI metrics support

### ISSUE THREAD

**Issue by ricibald** [MicrosoftDocs/azure-docs.it-it#437]
PowerBI "Supports logs but not metrics" is not true, I have realized a PowerBI that reads from metrics using REST API.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 7eae3c08-ec6d-7582-d4d9-59de75c0e252
* Version Independent ID: 97123dec-34d3-2cde-8060-e7c0e0d4e87f
* Content: [Visualizzazione dei dati da Monitoraggio di Azure](https://docs.microsoft.com/it-it/azure/azure-monitor/visualizations#feedback)
* Content Source: [articles/azure-monitor/visualizations.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/azure-monitor/visualizations.md)
* Sub-service: ****
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @ricibald
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @ricibald , 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @ricibald , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @ricibald , 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
