### ISSUE TITLE
Restrict inbound IP only for other Logic Apps

### ISSUE THREAD

**Issue by DanieleG90** [MicrosoftDocs/azure-docs.it-it#447]
How can I add "Only other logic apps" filter on Json instead of IP ranges for Restrict inbound IP ranges in Azure Resource Manager template?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 95b48753-cabe-fe92-42de-21775f4f99c3
* Version Independent ID: 45a1fa90-c4f8-6d0b-e1a8-ed996de671eb
* Content: [Proteggere l'accesso ai dati - Azure Logic Apps](https://docs.microsoft.com/it-it/azure/logic-apps/logic-apps-securing-a-logic-app#feedback)
* Content Source: [articles/logic-apps/logic-apps-securing-a-logic-app.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/logic-apps/logic-apps-securing-a-logic-app.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by ecfan** [comment]
Hi @DanieleG90, 

Thanks for your question! A doc update should appear in the [English version for this page](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app#restrict-inbound-ip-ranges-in-azure-resource-manager-template) on 11/06/2020 after 11 AM Pacific Time with the Italian version to follow shortly after, but I'm including a preview here below.

![image](https://user-images.githubusercontent.com/13206671/98332703-03027880-1fb4-11eb-84b9-a3f1b566187a.png)

**Comment by ecfan** [comment]
Actually, the #please-close command doesn't seem to work, so feel free to close the issue. Thanks!

**Comment by SunnyDeng** [comment]
Thank you @DanieleG90  for your feedback. Please kindly check https://github.com/MicrosoftDocs/azure-docs/issues/65840 for the further respond from @ecfan .
