### ISSUE TITLE
Account google con autenticazione a due fattori login fallito

### ISSUE THREAD

**Issue by LudoviKush** [MicrosoftDocs/azure-docs.it-it#85]
Non mi permette di effettuare il login poichè ho abilitata l'autenticazione  a due fattori, non accetta la password inserita benchè sia corretta

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 17e8e2a4-f278-c6d4-aafa-8b95c4c5c1ea
* Version Independent ID: 3d1f3907-392a-8edd-d625-1ab6cca393fa
* Content: [Risoluzione dei problemi di verifica in due passaggi](https://docs.microsoft.com/it-it/azure/multi-factor-authentication/end-user/multi-factor-authentication-end-user-troubleshoot)
* Content Source: [articles/multi-factor-authentication/end-user/multi-factor-authentication-end-user-troubleshoot.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/multi-factor-authentication/end-user/multi-factor-authentication-end-user-troubleshoot.md)
* Service: **multi-factor-authentication**
* Product: **unspecified**
* GitHub Login: @barlanmsft
* Microsoft Alias: **barlan**

**Comment by CeciAc** [comment]
Salve, @LudoviKush 

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione. 
Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti" nella parte inferiore della pagina DOCS. 

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale. 
Il tuo contributo ai nostri articoli è molto apprezzato.  

Cordiali saluti, 
Il team internazionale Microsoft Docs

**Comment by Sara-Nicolini** [comment]
@LudoviKush, puoi utiilzzare il pulsante "Commenti sul prodotto" anziché "Commenti sul contenuto" in quanto il commento è relativo al funzionamento del prodotto.
