### ISSUE TITLE
Dubbio

### ISSUE THREAD

**Issue by danieledc** [MicrosoftDocs/azure-docs.it-it#86]
Non mi è chiaro se lo script nella sezione "Acquisizione dell'ID utente" va a sostituire quello precedente (qullo nella sezione "Aggiungere lo script alle pagine Web" per intenderci) o se va in aggiunta.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: a1d5591a-bdb0-7eed-9697-4f2c7f3cc807
* Version Independent ID: 301d5ed0-863e-7a46-0d93-023f27e29f89
* Content: [Monitorare un sito di SharePoint con Application Insights](https://docs.microsoft.com/it-it/azure/application-insights/app-insights-sharepoint)
* Content Source: [articles/application-insights/app-insights-sharepoint.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/application-insights/app-insights-sharepoint.md)
* Service: **application-insights**
* Product: **unspecified**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by CeciAc** [comment]
Salve, @danieledc, 

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione. 
Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS. 

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale. 
Il tuo contributo ai nostri articoli è molto apprezzato.  

Cordiali saluti, 
Il team internazionale Microsoft Docs
