### ISSUE TITLE
Immagine errata

### ISSUE THREAD

**Issue by blkt** [MicrosoftDocs/azure-docs.it-it#87]
L'immagine cita "grafico" dove dovrebbe essere scritto "grafo".

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 42c7bf55-9a9e-9e54-15db-15c59a80d471
* Version Independent ID: b32d0d9a-99fd-9721-e093-54dfd43543ad
* Content: [Introduzione ad Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/introduction#feedback)
* Content Source: [articles/cosmos-db/introduction.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/cosmos-db/introduction.md)
* Service: **cosmos-db**
* GitHub Login: @mimig1
* Microsoft Alias: **mimig**

**Comment by gosali** [comment]
Hello, @blkt , 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Salve, @blkt ,

Grazie per i commenti e i suggerimenti inviati. 

Il nostro team linguistico ha esaminato e accettato i suggerimenti inviati. I suggerimenti sono stati implementati e pubblicati negli articoli aggiornati sul sito Docs nelle pagine seguenti https://docs.microsoft.com/it-it/azure/cosmos-db/introduction#feedback  

Il tuo contributo ai nostri articoli è molto apprezzato e ci auguriamo che vorrai continuare a inviarci i tuoi utili suggerimenti. 

Cordiali saluti, 
Il team internazionale Microsoft Docs
