### ISSUE TITLE
Error on creating a Streaming Analytics Job

### ISSUE THREAD

**Issue by NommySkies** [MicrosoftDocs/azure-docs.it-it#89]
"code":"InvalidDeploymentParameterValue" wich is set to NULL and I can't change it or know wich value I need to insert

---
#### Dettagli documento

⚠ *Non modificare questa sezione. È obbligatoria per il collegamento del problema fra docs.microsoft.com e GitHub.*

* ID: 97ce2614-0e74-0f67-bf3f-8a477bd5f329
* Version Independent ID: e29a2f4e-63a3-2f28-35bf-6d990f9f3b84
* Content: [Visualizzazione in tempo reale dei dati del sensore dall'hub IoT di Azure - Power BI](https://docs.microsoft.com/it-ch/azure/iot-hub/iot-hub-live-data-visualization-in-power-bi)
* Content Source: [articles/iot-hub/iot-hub-live-data-visualization-in-power-bi.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/iot-hub/iot-hub-live-data-visualization-in-power-bi.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by DavidPrio** [comment]
Hello, @NommySkies ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
Hello, @NommySkies ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation, and this seems to be related to the product itself. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
