### ISSUE TITLE
Size of the bubble correlating to the elevation of the volcano.

### ISSUE THREAD

**Issue by guerrieroi** [MicrosoftDocs/azure-docs.it-it#91]
I didn't understand how to correlate the Elevation value to the size property. Power BI ask to set only a Count of Elevation. The result was bubble size = 1 for all.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: db43c478-6301-7b69-131a-c4289797c49d
* Version Independent ID: 5f991bdb-919e-f712-1fe0-050eba25ebaf
* Content: [Esercitazione su Power BI per il connettore Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/powerbi-visualize)
* Content Source: [articles/cosmos-db/powerbi-visualize.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/cosmos-db/powerbi-visualize.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by LisandroSu** [comment]
Hello, @guerrieroi 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13837](https://github.com/MicrosoftDocs/azure-docs/issues/13837) via [**ZenHub**](https://www.zenhub.com/)
