### ISSUE TITLE
For running this sample in Django in IIS

### ISSUE THREAD

**Issue by nicogis** [MicrosoftDocs/azure-docs.it-it#95]
My configuration: Python 2.7.14 - Django 1.11.16 - Windows Server 2016

In web.config I have set 
&lt;add key="WSGI_HANDLER" value="django.core.wsgi.get_wsgi_application()" /&gt;

In urls.py
from django.conf.urls import url
from helloworld.views import home
urlpatterns = [
   url(r'^$', home, name='home'),
]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ffb8d659-5c8e-c3a9-3060-facce1593cfc
* Version Independent ID: 776e5786-711e-33ba-7522-10d78fea076a
* Content: [App Web Django in una macchina virtuale Windows Server in Azure](https://docs.microsoft.com/it-it/azure/virtual-machines/windows/classic/python-django-web-app)
* Content Source: [articles/virtual-machines/windows/classic/python-django-web-app.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/virtual-machines/windows/classic/python-django-web-app.md)
* Service: **virtual-machines-windows**
* GitHub Login: @huguesv
* Microsoft Alias: **huvalo**

**Comment by CeciAc** [comment]
Hello, @nicogis,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
