### ISSUE TITLE
Not save Document

### ISSUE THREAD

**Issue by 86simonepenna** [MicrosoftDocs/azure-docs.it-it#97]
response of CreateDocumentAsync is "Created", but in azure explorer document not exist. Why? db and collection created successfully.

Thank you

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 557827fd-e323-7b37-2fb8-a2b6d5c10811
* Version Independent ID: 9b04167b-a8f8-d252-971e-e39b181ce589
* Content: [Azure Cosmos DB: introduzione all'API SQL con l'esercitazione per .NET Core](https://docs.microsoft.com/it-it/azure/cosmos-db/sql-api-dotnetcore-get-started)
* Content Source: [articles/cosmos-db/sql-api-dotnetcore-get-started.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/cosmos-db/sql-api-dotnetcore-get-started.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by CeciAc** [comment]
Hello, @86simonepenna 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
